cache:
  directories:
  - $HOME/.m2
language: java
jdk: oraclejdk8
install:
  - mvn -B -Pdeploy -V dependency:go-offline
script:
  - mvn -B -Pdeploy -Dgpg.skip=true verify
notifications:
  email:
    - ben.alex@acegi.com.au
